#!/usr/bin/env python

import os
import shutil
from distutils.dir_util import copy_tree
from pathlib import Path
from tempfile import TemporaryDirectory
from huggingface_hub import snapshot_download

MODEL_REPO = "facebook/bart-large-mnli"
LOCAL_MODEL_DIR = './model'

if os.path.exists(LOCAL_MODEL_DIR):
    shutil.rmtree(LOCAL_MODEL_DIR)

# setup temporary directory
with TemporaryDirectory() as tmpdir:
    # download snapshot
    snapshot_dir = snapshot_download(
        repo_id=MODEL_REPO, 
        cache_dir=tmpdir,
        allow_patterns=["*.bin", "*.json", "*.md"],
    )
    # copy snapshot to model dir
    copy_tree(snapshot_dir, str(LOCAL_MODEL_DIR))

