#!/usr/bin/env python

import os
import shutil

from huggingface_hub import snapshot_download
from transformers import AutoTokenizer, AutoModelForSequenceClassification

MODEL_REPO = "facebook/bart-large-mnli"
CACHE_DIR = 'weights'
# snapshot_download(
#     repo_id=MODEL_REPO, 
#     allow_patterns=["*.bin", "*.json", "*.md"],
#     local_dir = CACHE_DIR,
#     cache_dir = CACHE_DIR,
#     local_dir_use_symlinks="auto",
#     )

model = AutoModelForSequenceClassification.from_pretrained(MODEL_REPO, cache_dir=CACHE_DIR)
tokenizer = AutoTokenizer.from_pretrained(MODEL_REPO, cache_dir=CACHE_DIR)